language: python

matrix:
  include:
    - name: "Python 2.7 on Xenial"
      python: 2.7
      dist: xenial
      addons:
        apt:
          packages:
          - libsndfile1-dev
          - libasound2-dev
    - name: "Python 2.7 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell       # 'language: python' causes errors on Travis CI macOS
      addons:
        homebrew:
          packages:
          - libsndfile
      before_script:
        - pip install pytest

install:
  - pip install -e .
script:
  - pytest