from numpy.distutils.misc_util import get_numpy_include_dirs

env = Environment()
env.Append(CFLAGS=Split("-W -Wall -Wextra -g"))
env.Append(CPPPATH=get_numpy_include_dirs() + ['/usr/include/python2.5'])
env.Append(LIBS = "asound")

env.LoadableModule("_alsa_backend.c", LDMODULEPREFIX="")
env.Program("enumerate.c", LIBS=['asound'])
