# This was generated by cycodegelib, please do not edit
# Generated by command /Users/david/local/bin/xml2cython.py -o AudioHardware.pxd -l CoreAudio CoreAudio/AudioHardware.h AudioHardware.xml
# Codegenlib version: 0.3dev
cdef extern from 'CoreAudio/AudioHardware.h':
	cdef enum:
		kAppleLosslessFormatFlag_16BitSourceData = 1
		kAppleLosslessFormatFlag_20BitSourceData = 2
		kAppleLosslessFormatFlag_24BitSourceData = 3
		kAppleLosslessFormatFlag_32BitSourceData = 4
		kAudioAggregateDeviceClassID = 1633773415
		kAudioAggregateDevicePropertyActiveSubDeviceList = 1634169456
		kAudioAggregateDevicePropertyComposition = 1633906541
		kAudioAggregateDevicePropertyFullSubDeviceList = 1735554416
		kAudioAggregateDevicePropertyMasterSubDevice = 1634562932
		kAudioBooleanControlClassID = 1953458028
		kAudioBooleanControlPropertyValue = 1650685548
		kAudioBootChimeVolumeControlClassID = 1886544237
		kAudioChannelBit_Center = 4
		kAudioChannelBit_CenterSurround = 256
		kAudioChannelBit_LFEScreen = 8
		kAudioChannelBit_Left = 1
		kAudioChannelBit_LeftCenter = 64
		kAudioChannelBit_LeftSurround = 16
		kAudioChannelBit_LeftSurroundDirect = 512
		kAudioChannelBit_Right = 2
		kAudioChannelBit_RightCenter = 128
		kAudioChannelBit_RightSurround = 32
		kAudioChannelBit_RightSurroundDirect = 1024
		kAudioChannelBit_TopBackCenter = 65536
		kAudioChannelBit_TopBackLeft = 32768
		kAudioChannelBit_TopBackRight = 131072
		kAudioChannelBit_TopCenterSurround = 2048
		kAudioChannelBit_VerticalHeightCenter = 8192
		kAudioChannelBit_VerticalHeightLeft = 4096
		kAudioChannelBit_VerticalHeightRight = 16384
		kAudioChannelCoordinates_Azimuth = 0
		kAudioChannelCoordinates_BackFront = 1
		kAudioChannelCoordinates_Distance = 2
		kAudioChannelCoordinates_DownUp = 2
		kAudioChannelCoordinates_Elevation = 1
		kAudioChannelCoordinates_LeftRight = 0
		kAudioChannelFlags_AllOff = 0
		kAudioChannelFlags_Meters = 4
		kAudioChannelFlags_RectangularCoordinates = 1
		kAudioChannelFlags_SphericalCoordinates = 2
		kAudioChannelLabel_Ambisonic_W = 200
		kAudioChannelLabel_Ambisonic_X = 201
		kAudioChannelLabel_Ambisonic_Y = 202
		kAudioChannelLabel_Ambisonic_Z = 203
		kAudioChannelLabel_Center = 3
		kAudioChannelLabel_CenterSurround = 9
		kAudioChannelLabel_CenterSurroundDirect = 44
		kAudioChannelLabel_ClickTrack = 304
		kAudioChannelLabel_DialogCentricMix = 43
		kAudioChannelLabel_Discrete = 400
		kAudioChannelLabel_Discrete_0 = 65536
		kAudioChannelLabel_Discrete_1 = 65537
		kAudioChannelLabel_Discrete_10 = 65546
		kAudioChannelLabel_Discrete_11 = 65547
		kAudioChannelLabel_Discrete_12 = 65548
		kAudioChannelLabel_Discrete_13 = 65549
		kAudioChannelLabel_Discrete_14 = 65550
		kAudioChannelLabel_Discrete_15 = 65551
		kAudioChannelLabel_Discrete_2 = 65538
		kAudioChannelLabel_Discrete_3 = 65539
		kAudioChannelLabel_Discrete_4 = 65540
		kAudioChannelLabel_Discrete_5 = 65541
		kAudioChannelLabel_Discrete_6 = 65542
		kAudioChannelLabel_Discrete_65535 = 131071
		kAudioChannelLabel_Discrete_7 = 65543
		kAudioChannelLabel_Discrete_8 = 65544
		kAudioChannelLabel_Discrete_9 = 65545
		kAudioChannelLabel_ForeignLanguage = 305
		kAudioChannelLabel_Haptic = 45
		kAudioChannelLabel_HeadphonesLeft = 301
		kAudioChannelLabel_HeadphonesRight = 302
		kAudioChannelLabel_HearingImpaired = 40
		kAudioChannelLabel_LFE2 = 37
		kAudioChannelLabel_LFEScreen = 4
		kAudioChannelLabel_Left = 1
		kAudioChannelLabel_LeftCenter = 7
		kAudioChannelLabel_LeftSurround = 5
		kAudioChannelLabel_LeftSurroundDirect = 10
		kAudioChannelLabel_LeftTotal = 38
		kAudioChannelLabel_LeftWide = 35
		kAudioChannelLabel_MS_Mid = 204
		kAudioChannelLabel_MS_Side = 205
		kAudioChannelLabel_Mono = 42
		kAudioChannelLabel_Narration = 41
		kAudioChannelLabel_RearSurroundLeft = 33
		kAudioChannelLabel_RearSurroundRight = 34
		kAudioChannelLabel_Right = 2
		kAudioChannelLabel_RightCenter = 8
		kAudioChannelLabel_RightSurround = 6
		kAudioChannelLabel_RightSurroundDirect = 11
		kAudioChannelLabel_RightTotal = 39
		kAudioChannelLabel_RightWide = 36
		kAudioChannelLabel_TopBackCenter = 17
		kAudioChannelLabel_TopBackLeft = 16
		kAudioChannelLabel_TopBackRight = 18
		kAudioChannelLabel_TopCenterSurround = 12
		kAudioChannelLabel_Unknown = -1
		kAudioChannelLabel_Unused = 0
		kAudioChannelLabel_UseCoordinates = 100
		kAudioChannelLabel_VerticalHeightCenter = 14
		kAudioChannelLabel_VerticalHeightLeft = 13
		kAudioChannelLabel_VerticalHeightRight = 15
		kAudioChannelLabel_XY_X = 206
		kAudioChannelLabel_XY_Y = 207
		kAudioChannelLayoutTag_AAC_3_0 = 7471107
		kAudioChannelLayoutTag_AAC_4_0 = 7602180
		kAudioChannelLayoutTag_AAC_5_0 = 7864325
		kAudioChannelLayoutTag_AAC_5_1 = 8126470
		kAudioChannelLayoutTag_AAC_6_0 = 9240582
		kAudioChannelLayoutTag_AAC_6_1 = 9306119
		kAudioChannelLayoutTag_AAC_7_0 = 9371655
		kAudioChannelLayoutTag_AAC_7_1 = 8323080
		kAudioChannelLayoutTag_AAC_Octagonal = 9437192
		kAudioChannelLayoutTag_AAC_Quadraphonic = 7077892
		kAudioChannelLayoutTag_AC3_1_0_1 = 9764866
		kAudioChannelLayoutTag_AC3_2_1_1 = 10027012
		kAudioChannelLayoutTag_AC3_3_0 = 9830403
		kAudioChannelLayoutTag_AC3_3_0_1 = 9961476
		kAudioChannelLayoutTag_AC3_3_1 = 9895940
		kAudioChannelLayoutTag_AC3_3_1_1 = 10092549
		kAudioChannelLayoutTag_Ambisonic_B_Format = 7012356
		kAudioChannelLayoutTag_AudioUnit_4 = 7077892
		kAudioChannelLayoutTag_AudioUnit_5 = 7143429
		kAudioChannelLayoutTag_AudioUnit_5_0 = 7733253
		kAudioChannelLayoutTag_AudioUnit_5_1 = 7929862
		kAudioChannelLayoutTag_AudioUnit_6 = 7208966
		kAudioChannelLayoutTag_AudioUnit_6_0 = 9109510
		kAudioChannelLayoutTag_AudioUnit_6_1 = 8192007
		kAudioChannelLayoutTag_AudioUnit_7_0 = 9175047
		kAudioChannelLayoutTag_AudioUnit_7_0_Front = 9699335
		kAudioChannelLayoutTag_AudioUnit_7_1 = 8388616
		kAudioChannelLayoutTag_AudioUnit_7_1_Front = 8257544
		kAudioChannelLayoutTag_AudioUnit_8 = 7274504
		kAudioChannelLayoutTag_Binaural = 6946818
		kAudioChannelLayoutTag_Cube = 7340040
		kAudioChannelLayoutTag_DVD_0 = 6553601
		kAudioChannelLayoutTag_DVD_1 = 6619138
		kAudioChannelLayoutTag_DVD_10 = 8912900
		kAudioChannelLayoutTag_DVD_11 = 8978437
		kAudioChannelLayoutTag_DVD_12 = 7929862
		kAudioChannelLayoutTag_DVD_13 = 7536644
		kAudioChannelLayoutTag_DVD_14 = 7667717
		kAudioChannelLayoutTag_DVD_15 = 8912900
		kAudioChannelLayoutTag_DVD_16 = 8978437
		kAudioChannelLayoutTag_DVD_17 = 7929862
		kAudioChannelLayoutTag_DVD_18 = 9043973
		kAudioChannelLayoutTag_DVD_19 = 7733253
		kAudioChannelLayoutTag_DVD_2 = 8585219
		kAudioChannelLayoutTag_DVD_20 = 7995398
		kAudioChannelLayoutTag_DVD_3 = 8650756
		kAudioChannelLayoutTag_DVD_4 = 8716291
		kAudioChannelLayoutTag_DVD_5 = 8781828
		kAudioChannelLayoutTag_DVD_6 = 8847365
		kAudioChannelLayoutTag_DVD_7 = 7405571
		kAudioChannelLayoutTag_DVD_8 = 7536644
		kAudioChannelLayoutTag_DVD_9 = 7667717
		kAudioChannelLayoutTag_DiscreteInOrder = 9633792
		kAudioChannelLayoutTag_Emagic_Default_7_1 = 8454152
		kAudioChannelLayoutTag_Hexagonal = 7208966
		kAudioChannelLayoutTag_ITU_1_0 = 6553601
		kAudioChannelLayoutTag_ITU_2_0 = 6619138
		kAudioChannelLayoutTag_ITU_2_1 = 8585219
		kAudioChannelLayoutTag_ITU_2_2 = 8650756
		kAudioChannelLayoutTag_ITU_3_0 = 7405571
		kAudioChannelLayoutTag_ITU_3_1 = 7536644
		kAudioChannelLayoutTag_ITU_3_2 = 7667717
		kAudioChannelLayoutTag_ITU_3_2_1 = 7929862
		kAudioChannelLayoutTag_ITU_3_4_1 = 8388616
		kAudioChannelLayoutTag_MPEG_1_0 = 6553601
		kAudioChannelLayoutTag_MPEG_2_0 = 6619138
		kAudioChannelLayoutTag_MPEG_3_0_A = 7405571
		kAudioChannelLayoutTag_MPEG_3_0_B = 7471107
		kAudioChannelLayoutTag_MPEG_4_0_A = 7536644
		kAudioChannelLayoutTag_MPEG_4_0_B = 7602180
		kAudioChannelLayoutTag_MPEG_5_0_A = 7667717
		kAudioChannelLayoutTag_MPEG_5_0_B = 7733253
		kAudioChannelLayoutTag_MPEG_5_0_C = 7798789
		kAudioChannelLayoutTag_MPEG_5_0_D = 7864325
		kAudioChannelLayoutTag_MPEG_5_1_A = 7929862
		kAudioChannelLayoutTag_MPEG_5_1_B = 7995398
		kAudioChannelLayoutTag_MPEG_5_1_C = 8060934
		kAudioChannelLayoutTag_MPEG_5_1_D = 8126470
		kAudioChannelLayoutTag_MPEG_6_1_A = 8192007
		kAudioChannelLayoutTag_MPEG_7_1_A = 8257544
		kAudioChannelLayoutTag_MPEG_7_1_B = 8323080
		kAudioChannelLayoutTag_MPEG_7_1_C = 8388616
		kAudioChannelLayoutTag_MatrixStereo = 6750210
		kAudioChannelLayoutTag_MidSide = 6815746
		kAudioChannelLayoutTag_Mono = 6553601
		kAudioChannelLayoutTag_Octagonal = 7274504
		kAudioChannelLayoutTag_Pentagonal = 7143429
		kAudioChannelLayoutTag_Quadraphonic = 7077892
		kAudioChannelLayoutTag_SMPTE_DTV = 8519688
		kAudioChannelLayoutTag_Stereo = 6619138
		kAudioChannelLayoutTag_StereoHeadphones = 6684674
		kAudioChannelLayoutTag_TMH_10_2_full = 9568277
		kAudioChannelLayoutTag_TMH_10_2_std = 9502736
		kAudioChannelLayoutTag_Unknown = -65536
		kAudioChannelLayoutTag_UseChannelBitmap = 65536
		kAudioChannelLayoutTag_UseChannelDescriptions = 0
		kAudioChannelLayoutTag_XY = 6881282
		kAudioClockSourceControlClassID = 1668047723
		kAudioClockSourceControlPropertyItemKind = 1668049771
		kAudioControlClassID = 1633907820
		kAudioControlPropertyElement = 1667591277
		kAudioControlPropertyScope = 1668506480
		kAudioControlPropertyVariant = 1668702578
		kAudioDataDestinationControlClassID = 1684370292
		kAudioDataSourceControlClassID = 1685287523
		kAudioDeviceClassID = 1633969526
		kAudioDevicePermissionsError = 560492391
		kAudioDeviceProcessorOverload = 1870030194
		kAudioDevicePropertyActualSampleRate = 1634955892
		kAudioDevicePropertyAvailableNominalSampleRates = 1853059619
		kAudioDevicePropertyBufferFrameSize = 1718839674
		kAudioDevicePropertyBufferFrameSizeRange = 1718843939
		kAudioDevicePropertyBufferSize = 1651730810
		kAudioDevicePropertyBufferSizeRange = 1651735075
		kAudioDevicePropertyChannelCategoryName = 1667460717
		kAudioDevicePropertyChannelCategoryNameCFString = 1818452846
		kAudioDevicePropertyChannelName = 1667788397
		kAudioDevicePropertyChannelNameCFString = 1818454126
		kAudioDevicePropertyChannelNominalLineLevel = 1852601964
		kAudioDevicePropertyChannelNominalLineLevelNameForID = 1668181110
		kAudioDevicePropertyChannelNominalLineLevelNameForIDCFString = 1818455660
		kAudioDevicePropertyChannelNominalLineLevels = 1852601891
		kAudioDevicePropertyChannelNumberName = 1668181613
		kAudioDevicePropertyChannelNumberNameCFString = 1818455662
		kAudioDevicePropertyClockDomain = 1668049764
		kAudioDevicePropertyClockSource = 1668510307
		kAudioDevicePropertyClockSourceKindForID = 1668506475
		kAudioDevicePropertyClockSourceNameForID = 1668506478
		kAudioDevicePropertyClockSourceNameForIDCFString = 1818456942
		kAudioDevicePropertyClockSources = 1668506403
		kAudioDevicePropertyConfigurationApplication = 1667330160
		kAudioDevicePropertyDataSource = 1936945763
		kAudioDevicePropertyDataSourceNameForID = 1936941934
		kAudioDevicePropertyDataSourceNameForIDCFString = 1819501422
		kAudioDevicePropertyDataSources = 1936941859
		kAudioDevicePropertyDeviceCanBeDefaultDevice = 1684434036
		kAudioDevicePropertyDeviceCanBeDefaultSystemDevice = 1936092276
		kAudioDevicePropertyDeviceHasChanged = 1684629094
		kAudioDevicePropertyDeviceIsAlive = 1818850926
		kAudioDevicePropertyDeviceIsRunning = 1735354734
		kAudioDevicePropertyDeviceIsRunningSomewhere = 1735356005
		kAudioDevicePropertyDeviceManufacturer = 1835101042
		kAudioDevicePropertyDeviceManufacturerCFString = 1819107691
		kAudioDevicePropertyDeviceName = 1851878757
		kAudioDevicePropertyDeviceNameCFString = 1819173229
		kAudioDevicePropertyDeviceUID = 1969841184
		kAudioDevicePropertyDriverShouldOwniSub = 1769174370
		kAudioDevicePropertyHogMode = 1869180523
		kAudioDevicePropertyIOCycleUsage = 1852012899
		kAudioDevicePropertyIOProcStreamUsage = 1937077093
		kAudioDevicePropertyJackIsConnected = 1784767339
		kAudioDevicePropertyLatency = 1819569763
		kAudioDevicePropertyModelUID = 1836411236
		kAudioDevicePropertyMute = 1836414053
		kAudioDevicePropertyNominalSampleRate = 1853059700
		kAudioDevicePropertyPlayThru = 1953002101
		kAudioDevicePropertyPlayThruDestination = 1835295859
		kAudioDevicePropertyPlayThruDestinationNameForID = 1835295854
		kAudioDevicePropertyPlayThruDestinationNameForIDCFString = 1835295843
		kAudioDevicePropertyPlayThruDestinations = 1835295779
		kAudioDevicePropertyPlayThruSolo = 1953002099
		kAudioDevicePropertyPlayThruStereoPan = 1836281966
		kAudioDevicePropertyPlayThruStereoPanChannels = 1836281891
		kAudioDevicePropertyPlayThruVolumeDecibels = 1836475490
		kAudioDevicePropertyPlayThruVolumeDecibelsToScalar = 1836462707
		kAudioDevicePropertyPlayThruVolumeRangeDecibels = 1836475427
		kAudioDevicePropertyPlayThruVolumeScalar = 1836479331
		kAudioDevicePropertyPlayThruVolumeScalarToDecibels = 1836462692
		kAudioDevicePropertyPlugIn = 1886156135
		kAudioDevicePropertyPreferredChannelLayout = 1936879204
		kAudioDevicePropertyPreferredChannelsForStereo = 1684236338
		kAudioDevicePropertyRegisterBufferList = 1919055206
		kAudioDevicePropertyRelatedDevices = 1634429294
		kAudioDevicePropertySafetyOffset = 1935763060
		kAudioDevicePropertyScopeInput = 1768845428
		kAudioDevicePropertyScopeOutput = 1869968496
		kAudioDevicePropertyScopePlayThrough = 1886679669
		kAudioDevicePropertySolo = 1936682095
		kAudioDevicePropertyStereoPan = 1936744814
		kAudioDevicePropertyStereoPanChannels = 1936748067
		kAudioDevicePropertyStreamConfiguration = 1936482681
		kAudioDevicePropertyStreamFormat = 1936092532
		kAudioDevicePropertyStreamFormatMatch = 1936092525
		kAudioDevicePropertyStreamFormatSupported = 1936092479
		kAudioDevicePropertyStreamFormats = 1936092451
		kAudioDevicePropertyStreams = 1937009955
		kAudioDevicePropertySubMute = 1936553332
		kAudioDevicePropertySubVolumeDecibels = 1937140836
		kAudioDevicePropertySubVolumeDecibelsToScalar = 1935946358
		kAudioDevicePropertySubVolumeRangeDecibels = 1937138723
		kAudioDevicePropertySubVolumeScalar = 1937140845
		kAudioDevicePropertySubVolumeScalarToDecibels = 1937125988
		kAudioDevicePropertySupportsMixing = 1835628607
		kAudioDevicePropertyTransportType = 1953653102
		kAudioDevicePropertyUsesVariableBufferFrameSizes = 1986425722
		kAudioDevicePropertyVolumeDecibels = 1987013732
		kAudioDevicePropertyVolumeDecibelsToScalar = 1684157046
		kAudioDevicePropertyVolumeRangeDecibels = 1986290211
		kAudioDevicePropertyVolumeScalar = 1987013741
		kAudioDevicePropertyVolumeScalarToDecibels = 1983013986
		kAudioDeviceStartTimeDontConsultDeviceFlag = 2
		kAudioDeviceStartTimeDontConsultHALFlag = 4
		kAudioDeviceStartTimeIsInputFlag = 1
		kAudioDeviceTransportTypeAggregate = 1735554416
		kAudioDeviceTransportTypeAutoAggregate = 1718055536
		kAudioDeviceUnknown = 0
		kAudioDeviceUnsupportedFormatError = 560226676
		kAudioFormat60958AC3 = 1667326771
		kAudioFormatAC3 = 1633889587
		kAudioFormatALaw = 1634492791
		kAudioFormatAMR = 1935764850
		kAudioFormatAppleIMA4 = 1768775988
		kAudioFormatAppleLossless = 1634492771
		kAudioFormatFlagIsAlignedHigh = 16
		kAudioFormatFlagIsBigEndian = 2
		kAudioFormatFlagIsFloat = 1
		kAudioFormatFlagIsNonInterleaved = 32
		kAudioFormatFlagIsNonMixable = 64
		kAudioFormatFlagIsPacked = 8
		kAudioFormatFlagIsSignedInteger = 4
		kAudioFormatFlagsAreAllClear = -2147483648
		kAudioFormatFlagsCanonical = 9
		kAudioFormatFlagsNativeEndian = 0
		kAudioFormatFlagsNativeFloatPacked = 9
		kAudioFormatLinearPCM = 1819304813
		kAudioFormatMACE3 = 1296122675
		kAudioFormatMACE6 = 1296122678
		kAudioFormatMIDIStream = 1835623529
		kAudioFormatMPEG4AAC = 1633772320
		kAudioFormatMPEG4AAC_HE = 1633772392
		kAudioFormatMPEG4AAC_HE_V2 = 1633772400
		kAudioFormatMPEG4AAC_LD = 1633772396
		kAudioFormatMPEG4AAC_Spatial = 1633772403
		kAudioFormatMPEG4CELP = 1667591280
		kAudioFormatMPEG4HVXC = 1752594531
		kAudioFormatMPEG4TwinVQ = 1953986161
		kAudioFormatMPEGLayer1 = 778924081
		kAudioFormatMPEGLayer2 = 778924082
		kAudioFormatMPEGLayer3 = 778924083
		kAudioFormatParameterValueStream = 1634760307
		kAudioFormatQDesign = 1363430723
		kAudioFormatQDesign2 = 1363430706
		kAudioFormatQUALCOMM = 1365470320
		kAudioFormatTimeCode = 1953066341
		kAudioFormatULaw = 1970037111
		kAudioHardwareBadDeviceError = 560227702
		kAudioHardwareBadObjectError = 560947818
		kAudioHardwareBadPropertySizeError = 561211770
		kAudioHardwareBadStreamError = 561214578
		kAudioHardwareIllegalOperationError = 1852797029
		kAudioHardwareNoError = 0
		kAudioHardwareNotRunningError = 1937010544
		kAudioHardwarePropertyBootChimeVolumeDecibels = 1650620004
		kAudioHardwarePropertyBootChimeVolumeDecibelsToScalar = 1650733686
		kAudioHardwarePropertyBootChimeVolumeRangeDecibels = 1650615331
		kAudioHardwarePropertyBootChimeVolumeScalar = 1650620019
		kAudioHardwarePropertyBootChimeVolumeScalarToDecibels = 1651913316
		kAudioHardwarePropertyDefaultInputDevice = 1682533920
		kAudioHardwarePropertyDefaultOutputDevice = 1682929012
		kAudioHardwarePropertyDefaultSystemOutputDevice = 1934587252
		kAudioHardwarePropertyDeviceForUID = 1685416292
		kAudioHardwarePropertyDevices = 1684370979
		kAudioHardwarePropertyHogModeIsAllowed = 1752131442
		kAudioHardwarePropertyIsInitingOrExiting = 1768845172
		kAudioHardwarePropertyPlugInForBundleID = 1885954665
		kAudioHardwarePropertyProcessIsMaster = 1835103092
		kAudioHardwarePropertyRunLoop = 1919839344
		kAudioHardwarePropertySleepingIsAllowed = 1936483696
		kAudioHardwarePropertyUnloadingIsAllowed = 1970170980
		kAudioHardwareUnknownPropertyError = 2003332927
		kAudioHardwareUnspecifiedError = 2003329396
		kAudioHardwareUnsupportedOperationError = 1970171760
		kAudioISubOwnerControlClassID = 1635017576
		kAudioJackControlClassID = 1784767339
		kAudioLFEMuteControlClassID = 1937072749
		kAudioLFEVolumeControlClassID = 1937072758
		kAudioLevelControlClassID = 1818588780
		kAudioLevelControlPropertyConvertDecibelsToScalar = 1818453107
		kAudioLevelControlPropertyConvertScalarToDecibels = 1818456932
		kAudioLevelControlPropertyDecibelRange = 1818453106
		kAudioLevelControlPropertyDecibelValue = 1818453110
		kAudioLevelControlPropertyScalarValue = 1818456950
		kAudioLineLevelControlClassID = 1852601964
		kAudioMuteControlClassID = 1836414053
		kAudioObjectClassID = 1634689642
		kAudioObjectClassIDWildcard = 707406378
		kAudioObjectPropertyClass = 1668047219
		kAudioObjectPropertyCreator = 1869638759
		kAudioObjectPropertyElementCategoryName = 1818452846
		kAudioObjectPropertyElementMaster = 0
		kAudioObjectPropertyElementName = 1818454126
		kAudioObjectPropertyElementNumberName = 1818455662
		kAudioObjectPropertyElementWildcard = -1
		kAudioObjectPropertyListenerAdded = 1818850145
		kAudioObjectPropertyListenerRemoved = 1818850162
		kAudioObjectPropertyManufacturer = 1819107691
		kAudioObjectPropertyName = 1819173229
		kAudioObjectPropertyOwnedObjects = 1870098020
		kAudioObjectPropertyOwner = 1937007734
		kAudioObjectPropertyScopeGlobal = 1735159650
		kAudioObjectPropertyScopeWildcard = 707406378
		kAudioObjectPropertySelectorWildcard = 707406378
		kAudioObjectSystemObject = 1
		kAudioObjectUnknown = 0
		kAudioPlugInClassID = 1634757735
		kAudioPlugInCreateAggregateDevice = 1667327847
		kAudioPlugInDestroyAggregateDevice = 1684105063
		kAudioPlugInPropertyBundleID = 1885956452
		kAudioPropertyWildcardChannel = -1
		kAudioPropertyWildcardPropertyID = 707406378
		kAudioPropertyWildcardSection = 255
		kAudioSelectorControlClassID = 1936483188
		kAudioSelectorControlPropertyAvailableItems = 1935892841
		kAudioSelectorControlPropertyCurrentItem = 1935893353
		kAudioSelectorControlPropertyItemName = 1935894894
		kAudioSoloControlClassID = 1936682095
		kAudioStereoPanControlClassID = 1936744814
		kAudioStereoPanControlPropertyPanningChannels = 1936745315
		kAudioStereoPanControlPropertyValue = 1936745334
		kAudioStreamAnyRate = 0
		kAudioStreamClassID = 1634956402
		kAudioStreamPropertyAvailablePhysicalFormats = 1885762657
		kAudioStreamPropertyAvailableVirtualFormats = 1936092513
		kAudioStreamPropertyDirection = 1935960434
		kAudioStreamPropertyLatency = 1819569763
		kAudioStreamPropertyOwningDevice = 1937007734
		kAudioStreamPropertyPhysicalFormat = 1885762592
		kAudioStreamPropertyPhysicalFormatMatch = 1885762669
		kAudioStreamPropertyPhysicalFormatSupported = 1885762623
		kAudioStreamPropertyPhysicalFormats = 1885762595
		kAudioStreamPropertyStartingChannel = 1935894638
		kAudioStreamPropertyTerminalType = 1952805485
		kAudioStreamPropertyVirtualFormat = 1936092532
		kAudioStreamUnknown = 0
		kAudioSubDeviceClassID = 1634956642
		kAudioSubDeviceDriftCompensationHighQuality = 96
		kAudioSubDeviceDriftCompensationLowQuality = 32
		kAudioSubDeviceDriftCompensationMaxQuality = 127
		kAudioSubDeviceDriftCompensationMediumQuality = 64
		kAudioSubDeviceDriftCompensationMinQuality = 0
		kAudioSubDevicePropertyDriftCompensation = 1685218932
		kAudioSubDevicePropertyDriftCompensationQuality = 1685218929
		kAudioSubDevicePropertyExtraLatency = 2020373603
		kAudioSystemObjectClassID = 1634957683
		kAudioTimeStampHostTimeValid = 2
		kAudioTimeStampRateScalarValid = 4
		kAudioTimeStampSMPTETimeValid = 16
		kAudioTimeStampSampleHostTimeValid = 3
		kAudioTimeStampSampleTimeValid = 1
		kAudioTimeStampWordClockTimeValid = 8
		kAudioVolumeControlClassID = 1986817381
		kLinearPCMFormatFlagIsAlignedHigh = 16
		kLinearPCMFormatFlagIsBigEndian = 2
		kLinearPCMFormatFlagIsFloat = 1
		kLinearPCMFormatFlagIsNonInterleaved = 32
		kLinearPCMFormatFlagIsNonMixable = 64
		kLinearPCMFormatFlagIsPacked = 8
		kLinearPCMFormatFlagIsSignedInteger = 4
		kLinearPCMFormatFlagsAreAllClear = -2147483648
		kMPEG4Object_AAC_LC = 2
		kMPEG4Object_AAC_LTP = 4
		kMPEG4Object_AAC_Main = 1
		kMPEG4Object_AAC_SBR = 5
		kMPEG4Object_AAC_SSR = 3
		kMPEG4Object_AAC_Scalable = 6
		kMPEG4Object_CELP = 8
		kMPEG4Object_HVXC = 9
		kMPEG4Object_TwinVQ = 7
		kSMPTETimeRunning = 2
		kSMPTETimeType2398 = 11
		kSMPTETimeType24 = 0
		kSMPTETimeType25 = 1
		kSMPTETimeType2997 = 4
		kSMPTETimeType2997Drop = 5
		kSMPTETimeType30 = 3
		kSMPTETimeType30Drop = 2
		kSMPTETimeType50 = 10
		kSMPTETimeType5994 = 7
		kSMPTETimeType5994Drop = 9
		kSMPTETimeType60 = 6
		kSMPTETimeType60Drop = 8
		kSMPTETimeValid = 1
	ctypedef double Float64
	ctypedef long long unsigned int UInt64
	ctypedef short int SInt16
	ctypedef long unsigned int UInt32
	cdef struct SMPTETime:
		SInt16 mSubframes
		SInt16 mSubframeDivisor
		UInt32 mCounter
		UInt32 mType
		UInt32 mFlags
		SInt16 mHours
		SInt16 mMinutes
		SInt16 mSeconds
		SInt16 mFrames
	ctypedef SMPTETime SMPTETime
	cdef struct AudioTimeStamp:
		Float64 mSampleTime
		UInt64 mHostTime
		Float64 mRateScalar
		UInt64 mWordClockTime
		SMPTETime mSMPTETime
		UInt32 mFlags
		UInt32 mReserved
	ctypedef AudioTimeStamp AudioTimeStamp
	ctypedef unsigned char Boolean
	ctypedef UInt32 AudioObjectPropertySelector
	ctypedef AudioObjectPropertySelector AudioDevicePropertyID
	ctypedef UInt32 AudioObjectID
	ctypedef AudioObjectID AudioDeviceID
	ctypedef long int SInt32
	ctypedef SInt32 OSStatus
	OSStatus AudioDeviceSetProperty(AudioDeviceID, AudioTimeStamp *, UInt32, Boolean, AudioDevicePropertyID, UInt32, void *)
	ctypedef OSStatus(*AudioDevicePropertyListenerProc)(AudioDeviceID, UInt32, Boolean, AudioDevicePropertyID, void *)
	OSStatus AudioDeviceRemovePropertyListener(AudioDeviceID, UInt32, Boolean, AudioDevicePropertyID, AudioDevicePropertyListenerProc)
	void FillOutAudioTimeStampWithSampleAndHostTime(AudioTimeStamp *, Float64, UInt64)
	cdef struct AudioBuffer:
		UInt32 mNumberChannels
		UInt32 mDataByteSize
		void * mData
	ctypedef AudioBuffer AudioBuffer
	cdef struct AudioBufferList:
		UInt32 mNumberBuffers
		AudioBuffer * mBuffers
	ctypedef AudioBufferList AudioBufferList
	ctypedef OSStatus(*AudioDeviceIOProc)(AudioDeviceID, AudioTimeStamp *, AudioBufferList *, AudioTimeStamp *, AudioBufferList *, AudioTimeStamp *, void *)
	OSStatus AudioDeviceStartAtTime(AudioDeviceID, AudioDeviceIOProc, AudioTimeStamp *, UInt32)
	ctypedef AudioObjectID AudioStreamID
	ctypedef OSStatus(*AudioStreamPropertyListenerProc)(AudioStreamID, UInt32, AudioDevicePropertyID, void *)
	OSStatus AudioStreamAddPropertyListener(AudioStreamID, UInt32, AudioDevicePropertyID, AudioStreamPropertyListenerProc, void *)
	OSStatus AudioDeviceGetProperty(AudioDeviceID, UInt32, Boolean, AudioDevicePropertyID, UInt32 *, void *)
	OSStatus AudioDeviceStart(AudioDeviceID, AudioDeviceIOProc)
	ctypedef UInt32 AudioObjectPropertyScope
	ctypedef UInt32 AudioObjectPropertyElement
	cdef struct AudioObjectPropertyAddress:
		AudioObjectPropertySelector mSelector
		AudioObjectPropertyScope mScope
		AudioObjectPropertyElement mElement
	ctypedef AudioObjectPropertyAddress AudioObjectPropertyAddress
	OSStatus AudioObjectSetPropertyData(AudioObjectID, AudioObjectPropertyAddress *, UInt32, void *, UInt32, void *)
	ctypedef OSStatus(*AudioObjectPropertyListenerProc)(AudioObjectID, UInt32, AudioObjectPropertyAddress *, void *)
	OSStatus AudioObjectAddPropertyListener(AudioObjectID, AudioObjectPropertyAddress *, AudioObjectPropertyListenerProc, void *)
	cdef struct __CFRunLoopSource:
		pass
	ctypedef __CFRunLoopSource * CFRunLoopSourceRef
	OSStatus AudioHardwareAddRunLoopSource(CFRunLoopSourceRef)
	OSStatus AudioStreamSetProperty(AudioStreamID, AudioTimeStamp *, UInt32, AudioDevicePropertyID, UInt32, void *)
	ctypedef AudioObjectPropertySelector AudioHardwarePropertyID
	OSStatus AudioHardwareGetProperty(AudioHardwarePropertyID, UInt32 *, void *)
	OSStatus AudioObjectRemovePropertyListener(AudioObjectID, AudioObjectPropertyAddress *, AudioObjectPropertyListenerProc, void *)
	OSStatus AudioDeviceGetNearestStartTime(AudioDeviceID, AudioTimeStamp *, UInt32)
	OSStatus AudioDeviceStop(AudioDeviceID, AudioDeviceIOProc)
	OSStatus AudioHardwareUnload()
	OSStatus AudioStreamGetProperty(AudioStreamID, UInt32, AudioDevicePropertyID, UInt32 *, void *)
	void FillOutAudioTimeStampWithSampleTime(AudioTimeStamp *, Float64)
	cdef struct AudioStreamBasicDescription:
		Float64 mSampleRate
		UInt32 mFormatID
		UInt32 mFormatFlags
		UInt32 mBytesPerPacket
		UInt32 mFramesPerPacket
		UInt32 mBytesPerFrame
		UInt32 mChannelsPerFrame
		UInt32 mBitsPerChannel
		UInt32 mReserved
	ctypedef AudioStreamBasicDescription AudioStreamBasicDescription
	void FillOutASBDForLPCM(AudioStreamBasicDescription *, Float64, UInt32, UInt32, UInt32, bool, bool, bool)
	OSStatus AudioDeviceAddIOProc(AudioDeviceID, AudioDeviceIOProc, void *)
	void FillOutAudioTimeStampWithHostTime(AudioTimeStamp *, UInt64)
	OSStatus AudioObjectGetPropertyData(AudioObjectID, AudioObjectPropertyAddress *, UInt32, void *, UInt32 *, void *)
	void AudioObjectShow(AudioObjectID)
	OSStatus AudioStreamRemovePropertyListener(AudioStreamID, UInt32, AudioDevicePropertyID, AudioStreamPropertyListenerProc)
	OSStatus AudioHardwareSetProperty(AudioHardwarePropertyID, UInt32, void *)
	bool IsAudioFormatNativeEndian(AudioStreamBasicDescription *)
	OSStatus AudioHardwareRemoveRunLoopSource(CFRunLoopSourceRef)
	OSStatus AudioDeviceGetCurrentTime(AudioDeviceID, AudioTimeStamp *)
	UInt32 CalculateLPCMFlags(UInt32, UInt32, bool, bool, bool)
	OSStatus AudioHardwareGetPropertyInfo(AudioHardwarePropertyID, UInt32 *, Boolean *)
	OSStatus AudioDeviceRemoveIOProc(AudioDeviceID, AudioDeviceIOProc)
	OSStatus AudioDeviceAddPropertyListener(AudioDeviceID, UInt32, Boolean, AudioDevicePropertyID, AudioDevicePropertyListenerProc, void *)
	Boolean AudioObjectHasProperty(AudioObjectID, AudioObjectPropertyAddress *)
	ctypedef OSStatus(*AudioHardwarePropertyListenerProc)(AudioHardwarePropertyID, void *)
	OSStatus AudioHardwareRemovePropertyListener(AudioHardwarePropertyID, AudioHardwarePropertyListenerProc)
	OSStatus AudioDeviceGetPropertyInfo(AudioDeviceID, UInt32, Boolean, AudioDevicePropertyID, UInt32 *, Boolean *)
	OSStatus AudioDeviceRead(AudioDeviceID, AudioTimeStamp *, AudioBufferList *)
	OSStatus AudioObjectIsPropertySettable(AudioObjectID, AudioObjectPropertyAddress *, Boolean *)
	OSStatus AudioHardwareAddPropertyListener(AudioHardwarePropertyID, AudioHardwarePropertyListenerProc, void *)
	OSStatus AudioDeviceTranslateTime(AudioDeviceID, AudioTimeStamp *, AudioTimeStamp *)
	OSStatus AudioObjectGetPropertyDataSize(AudioObjectID, AudioObjectPropertyAddress *, UInt32, void *, UInt32 *)
	OSStatus AudioStreamGetPropertyInfo(AudioStreamID, UInt32, AudioDevicePropertyID, UInt32 *, Boolean *)
