from numpy.distutils.misc_util import get_numpy_include_dirs

env = Environment()
env.Append(CFLAGS=Split("-W -Wall -Wextra"))
env.Append(CPPPATH=get_numpy_include_dirs() + ['/usr/include/python2.5'])
env.Append(FRAMEWORKS=["CoreAudio"])
env.Append(LDMODULEFLAGS=["-undefined", "dynamic_lookup"])

env.LoadableModule("macosx_backend.c", LDMODULEPREFIX="", LDMODULESUFFIX=".so")
env.Program("enumerate.c")
